# Lotus Per-App Configuration
# 0 = Off, 1 = Uinput (Smooth), 2 = Uinput (Slow), 3 = Uinput (Hardcore), 4 = Surrounding Text, 5 = Preedit, 6 = Emoji Picker
floorp=5
zen-bin=5
waterfox=5
zen=5
code=5
librewolf=5
antigravity=5
firefox=5
